version: '2'
services:
    wade-app:
        image: wade
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://wade-postgresql:5432/WADE
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=wade-elasticsearch:9300
        ports:
            - 8080:8080
    wade-postgresql:
        extends:
            file: postgresql.yml
            service: wade-postgresql
    wade-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: wade-elasticsearch
